import esbuild from 'esbuild';

async function main() {
	await esbuild.build({
		entryPoints: ['./iframe/js/header-silk/panel.js'],
		outfile: './iframe/js/header-silk.js',
		bundle: true,
		format: 'iife',
		platform: 'browser',
		target: ['es2018'],
		charset: 'utf8',
		minify: false,
		sourcemap: false,
		legalComments: 'none',
		banner: {
			js: '// Auto-generated from iframe/js/header-silk/*.js. Do not edit this file directly.',
		},
	});
}

void main();
